name: CI & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binary
        run: GOOS=linux GOARCH=amd64 go build -o sailboat

      - name: Create .ssh directory
        run: mkdir -p ~/.ssh && chmod 700 ~/.ssh

      - name: Add SSH private key
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add host to known_hosts
        run: ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: SCP binary to server
        run: |
          scp sailboat ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}

      - name: SSH and restart service
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "pkill sailboat || true && chmod +x ${{ secrets.DEPLOY_PATH }}/sailboat && nohup ${{ secrets.DEPLOY_PATH }}/sailboat > app.log 2>&1 &"
